model: "boundary_tbb"
data: "current_dataset/sonata_data_standardized.json"
fit_params:
  n_chains: 4
  warmup: 20
  num_samples: 20
  thin: 1
  threads_per_chain: 4
initial_path: "./python/initials.npy"